# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Documents/my_projects/Nautical-Navigation-Project/Qt_D - UIs/initial.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1322, 933)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.main_frame = QtGui.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.main_frame.setObjectName(_fromUtf8("main_frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.map_wynd = QtGui.QWidget(self.main_frame)
        self.map_wynd.setObjectName(_fromUtf8("map_wynd"))
        self.gridLayout = QtGui.QGridLayout(self.map_wynd)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.vertic_scroll = QtGui.QScrollBar(self.map_wynd)
        self.vertic_scroll.setOrientation(QtCore.Qt.Vertical)
        self.vertic_scroll.setObjectName(_fromUtf8("vertic_scroll"))
        self.gridLayout.addWidget(self.vertic_scroll, 0, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(self.map_wynd)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.horzn_scroll = QtGui.QScrollBar(self.map_wynd)
        self.horzn_scroll.setOrientation(QtCore.Qt.Horizontal)
        self.horzn_scroll.setObjectName(_fromUtf8("horzn_scroll"))
        self.gridLayout.addWidget(self.horzn_scroll, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.map_wynd)
        self.tool_frame = QtGui.QFrame(self.main_frame)
        self.tool_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tool_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.tool_frame.setObjectName(_fromUtf8("tool_frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tool_frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.tool_frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label, QtCore.Qt.AlignHCenter)
        self.line = QtGui.QFrame(self.tool_frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.pushButton = QtGui.QPushButton(self.tool_frame)
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.save_btn_toolfr = QtGui.QPushButton(self.tool_frame)
        self.save_btn_toolfr.setCheckable(False)
        self.save_btn_toolfr.setObjectName(_fromUtf8("save_btn_toolfr"))
        self.verticalLayout.addWidget(self.save_btn_toolfr)
        self.toggle_group = QtGui.QGroupBox(self.tool_frame)
        self.toggle_group.setMinimumSize(QtCore.QSize(104, 39))
        self.toggle_group.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.toggle_group.setObjectName(_fromUtf8("toggle_group"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.toggle_group)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.toggl_course = QtGui.QPushButton(self.toggle_group)
        self.toggl_course.setCheckable(True)
        self.toggl_course.setObjectName(_fromUtf8("toggl_course"))
        self.verticalLayout_2.addWidget(self.toggl_course, QtCore.Qt.AlignTop)
        self.toggl_traff = QtGui.QPushButton(self.toggle_group)
        self.toggl_traff.setCheckable(True)
        self.toggl_traff.setObjectName(_fromUtf8("toggl_traff"))
        self.verticalLayout_2.addWidget(self.toggl_traff)
        self.toggl_weather = QtGui.QPushButton(self.toggle_group)
        self.toggl_weather.setCheckable(True)
        self.toggl_weather.setObjectName(_fromUtf8("toggl_weather"))
        self.verticalLayout_2.addWidget(self.toggl_weather)
        self.toggl_waves = QtGui.QPushButton(self.toggle_group)
        self.toggl_waves.setCheckable(True)
        self.toggl_waves.setObjectName(_fromUtf8("toggl_waves"))
        self.verticalLayout_2.addWidget(self.toggl_waves)
        self.toggl_temp = QtGui.QPushButton(self.toggle_group)
        self.toggl_temp.setCheckable(True)
        self.toggl_temp.setObjectName(_fromUtf8("toggl_temp"))
        self.verticalLayout_2.addWidget(self.toggl_temp)
        self.verticalLayout.addWidget(self.toggle_group, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.tool_fr_seperator = QtGui.QFrame(self.tool_frame)
        self.tool_fr_seperator.setFrameShape(QtGui.QFrame.HLine)
        self.tool_fr_seperator.setFrameShadow(QtGui.QFrame.Sunken)
        self.tool_fr_seperator.setObjectName(_fromUtf8("tool_fr_seperator"))
        self.verticalLayout.addWidget(self.tool_fr_seperator)
        self.zoom_in_btn = QtGui.QPushButton(self.tool_frame)
        self.zoom_in_btn.setObjectName(_fromUtf8("zoom_in_btn"))
        self.verticalLayout.addWidget(self.zoom_in_btn)
        self.zoom_sldr = QtGui.QSlider(self.tool_frame)
        self.zoom_sldr.setBaseSize(QtCore.QSize(0, 0))
        self.zoom_sldr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zoom_sldr.setMouseTracking(True)
        self.zoom_sldr.setMaximum(10)
        self.zoom_sldr.setPageStep(10)
        self.zoom_sldr.setOrientation(QtCore.Qt.Vertical)
        self.zoom_sldr.setTickPosition(QtGui.QSlider.TicksAbove)
        self.zoom_sldr.setTickInterval(5)
        self.zoom_sldr.setObjectName(_fromUtf8("zoom_sldr"))
        self.verticalLayout.addWidget(self.zoom_sldr, QtCore.Qt.AlignHCenter)
        self.zoom_out_btn = QtGui.QPushButton(self.tool_frame)
        self.zoom_out_btn.setObjectName(_fromUtf8("zoom_out_btn"))
        self.verticalLayout.addWidget(self.zoom_out_btn)
        self.zoom_sldr.raise_()
        self.pushButton.raise_()
        self.tool_fr_seperator.raise_()
        self.save_btn_toolfr.raise_()
        self.toggle_group.raise_()
        self.label.raise_()
        self.line.raise_()
        self.zoom_in_btn.raise_()
        self.zoom_out_btn.raise_()
        self.horizontalLayout_2.addWidget(self.tool_frame)
        self.horizontalLayout_2.setStretch(0, 100)
        self.horizontalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menu_bar = QtGui.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 1322, 36))
        self.menu_bar.setObjectName(_fromUtf8("menu_bar"))
        self.file_menu = QtGui.QMenu(self.menu_bar)
        self.file_menu.setObjectName(_fromUtf8("file_menu"))
        self.edit_menu = QtGui.QMenu(self.menu_bar)
        self.edit_menu.setObjectName(_fromUtf8("edit_menu"))
        self.import_menu = QtGui.QMenu(self.menu_bar)
        self.import_menu.setObjectName(_fromUtf8("import_menu"))
        MainWindow.setMenuBar(self.menu_bar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.save_action = QtGui.QAction(MainWindow)
        self.save_action.setObjectName(_fromUtf8("save_action"))
        self.saveAs_action = QtGui.QAction(MainWindow)
        self.saveAs_action.setObjectName(_fromUtf8("saveAs_action"))
        self.Import_action = QtGui.QAction(MainWindow)
        self.Import_action.setObjectName(_fromUtf8("Import_action"))
        self.quit_action = QtGui.QAction(MainWindow)
        self.quit_action.setObjectName(_fromUtf8("quit_action"))
        self.actionImp_Boats = QtGui.QAction(MainWindow)
        self.actionImp_Boats.setObjectName(_fromUtf8("actionImp_Boats"))
        self.actionImp_Weather = QtGui.QAction(MainWindow)
        self.actionImp_Weather.setObjectName(_fromUtf8("actionImp_Weather"))
        self.actionImp_Temprature = QtGui.QAction(MainWindow)
        self.actionImp_Temprature.setObjectName(_fromUtf8("actionImp_Temprature"))
        self.actionImp_Waves = QtGui.QAction(MainWindow)
        self.actionImp_Waves.setObjectName(_fromUtf8("actionImp_Waves"))
        self.actionToggle_Course = QtGui.QAction(MainWindow)
        self.actionToggle_Course.setObjectName(_fromUtf8("actionToggle_Course"))
        self.actionToggle_Weather = QtGui.QAction(MainWindow)
        self.actionToggle_Weather.setCheckable(True)
        self.actionToggle_Weather.setObjectName(_fromUtf8("actionToggle_Weather"))
        self.actionToggle_Waves = QtGui.QAction(MainWindow)
        self.actionToggle_Waves.setCheckable(True)
        self.actionToggle_Waves.setObjectName(_fromUtf8("actionToggle_Waves"))
        self.actionToggle_Boats = QtGui.QAction(MainWindow)
        self.actionToggle_Boats.setCheckable(True)
        self.actionToggle_Boats.setObjectName(_fromUtf8("actionToggle_Boats"))
        self.actionToggle_Toolbar = QtGui.QAction(MainWindow)
        self.actionToggle_Toolbar.setCheckable(True)
        self.actionToggle_Toolbar.setObjectName(_fromUtf8("actionToggle_Toolbar"))
        self.actionToggle_Temprature = QtGui.QAction(MainWindow)
        self.actionToggle_Temprature.setObjectName(_fromUtf8("actionToggle_Temprature"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionCorner_Coordinates = QtGui.QAction(MainWindow)
        self.actionCorner_Coordinates.setObjectName(_fromUtf8("actionCorner_Coordinates"))
        self.actionPlot_Course = QtGui.QAction(MainWindow)
        self.actionPlot_Course.setCheckable(True)
        self.actionPlot_Course.setObjectName(_fromUtf8("actionPlot_Course"))
        self.file_menu.addAction(self.save_action)
        self.file_menu.addAction(self.saveAs_action)
        self.file_menu.addAction(self.Import_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.quit_action)
        self.file_menu.addAction(self.actionPreferences)
        self.edit_menu.addAction(self.actionCorner_Coordinates)
        self.import_menu.addAction(self.actionImp_Boats)
        self.import_menu.addAction(self.actionImp_Weather)
        self.import_menu.addAction(self.actionImp_Temprature)
        self.import_menu.addAction(self.actionImp_Waves)
        self.menu_bar.addAction(self.file_menu.menuAction())
        self.menu_bar.addAction(self.edit_menu.menuAction())
        self.menu_bar.addAction(self.import_menu.menuAction())

        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlot_Course)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">N-nav</span></p></body></html>", None))
        self.pushButton.setText(_translate("MainWindow", "Open", None))
        self.save_btn_toolfr.setText(_translate("MainWindow", "Save", None))
        self.toggle_group.setTitle(_translate("MainWindow", "Toggle", None))
        self.toggl_course.setText(_translate("MainWindow", "Course", None))
        self.toggl_traff.setText(_translate("MainWindow", "Traffic", None))
        self.toggl_weather.setText(_translate("MainWindow", "Weather", None))
        self.toggl_waves.setText(_translate("MainWindow", "Waves", None))
        self.toggl_temp.setText(_translate("MainWindow", "Temprature", None))
        self.zoom_in_btn.setText(_translate("MainWindow", "Zoom In", None))
        self.zoom_out_btn.setText(_translate("MainWindow", "Zoom Out", None))
        self.file_menu.setTitle(_translate("MainWindow", "File", None))
        self.edit_menu.setTitle(_translate("MainWindow", "Edit", None))
        self.import_menu.setTitle(_translate("MainWindow", "Import", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.save_action.setText(_translate("MainWindow", "Save", None))
        self.save_action.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.saveAs_action.setText(_translate("MainWindow", "Save As...", None))
        self.saveAs_action.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.Import_action.setText(_translate("MainWindow", "Import", None))
        self.Import_action.setShortcut(_translate("MainWindow", "Ctrl+I", None))
        self.quit_action.setText(_translate("MainWindow", "Quit", None))
        self.quit_action.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionImp_Boats.setText(_translate("MainWindow", "Boats", None))
        self.actionImp_Weather.setText(_translate("MainWindow", "Weather", None))
        self.actionImp_Temprature.setText(_translate("MainWindow", "Temprature", None))
        self.actionImp_Waves.setText(_translate("MainWindow", "Waves", None))
        self.actionToggle_Course.setText(_translate("MainWindow", "Toggle Course", None))
        self.actionToggle_Weather.setText(_translate("MainWindow", "ToggleWeather", None))
        self.actionToggle_Waves.setText(_translate("MainWindow", "Toggle Waves", None))
        self.actionToggle_Boats.setText(_translate("MainWindow", "Toggle Boats", None))
        self.actionToggle_Toolbar.setText(_translate("MainWindow", "View/Hide Toolbar", None))
        self.actionToggle_Temprature.setText(_translate("MainWindow", "Toggle Temprature", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionCorner_Coordinates.setText(_translate("MainWindow", "Corner Coordinates", None))
        self.actionPlot_Course.setText(_translate("MainWindow", "Plot Course", None))
        self.actionPlot_Course.setToolTip(_translate("MainWindow", "plot course", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

