# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_D - UIs/main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(904, 1149)
        self.central_widget = QtGui.QWidget(MainWindow)
        self.central_widget.setObjectName(_fromUtf8("central_widget"))
        self.central_widget_layout = QtGui.QHBoxLayout(self.central_widget)
        self.central_widget_layout.setObjectName(_fromUtf8("central_widget_layout"))
        self.mapcontr_splitter = QtGui.QSplitter(self.central_widget)
        self.mapcontr_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.mapcontr_splitter.setObjectName(_fromUtf8("mapcontr_splitter"))
        self.map_view_widget = QtGui.QWidget(self.mapcontr_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_view_widget.sizePolicy().hasHeightForWidth())
        self.map_view_widget.setSizePolicy(sizePolicy)
        self.map_view_widget.setObjectName(_fromUtf8("map_view_widget"))
        self.map_view_widget_layout = QtGui.QGridLayout(self.map_view_widget)
        self.map_view_widget_layout.setObjectName(_fromUtf8("map_view_widget_layout"))
        self.map_view = QtGui.QGraphicsView(self.map_view_widget)
        self.map_view.setObjectName(_fromUtf8("map_view"))
        self.map_view_widget_layout.addWidget(self.map_view, 0, 0, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.mapcontr_splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.control_panel = QtGui.QVBoxLayout(self.layoutWidget)
        self.control_panel.setObjectName(_fromUtf8("control_panel"))
        self.nnav_label = QtGui.QLabel(self.layoutWidget)
        self.nnav_label.setObjectName(_fromUtf8("nnav_label"))
        self.control_panel.addWidget(self.nnav_label)
        self.spacer_line_top = QtGui.QFrame(self.layoutWidget)
        self.spacer_line_top.setFrameShape(QtGui.QFrame.HLine)
        self.spacer_line_top.setFrameShadow(QtGui.QFrame.Sunken)
        self.spacer_line_top.setObjectName(_fromUtf8("spacer_line_top"))
        self.control_panel.addWidget(self.spacer_line_top)
        self.control_tabs = QtGui.QTabWidget(self.layoutWidget)
        self.control_tabs.setEnabled(True)
        self.control_tabs.setObjectName(_fromUtf8("control_tabs"))
        self.toggle_tab = QtGui.QWidget()
        self.toggle_tab.setObjectName(_fromUtf8("toggle_tab"))
        self.toggles_layout = QtGui.QHBoxLayout(self.toggle_tab)
        self.toggles_layout.setObjectName(_fromUtf8("toggles_layout"))
        self.toggles = QtGui.QVBoxLayout()
        self.toggles.setContentsMargins(0, -1, -1, -1)
        self.toggles.setObjectName(_fromUtf8("toggles"))
        self.toggl_course = QtGui.QRadioButton(self.toggle_tab)
        self.toggl_course.setCheckable(True)
        self.toggl_course.setAutoExclusive(False)
        self.toggl_course.setObjectName(_fromUtf8("toggl_course"))
        self.toggles.addWidget(self.toggl_course, QtCore.Qt.AlignTop)
        self.toggl_traff = QtGui.QRadioButton(self.toggle_tab)
        self.toggl_traff.setCheckable(True)
        self.toggl_traff.setAutoExclusive(False)
        self.toggl_traff.setObjectName(_fromUtf8("toggl_traff"))
        self.toggles.addWidget(self.toggl_traff, QtCore.Qt.AlignTop)
        self.toggl_weather = QtGui.QRadioButton(self.toggle_tab)
        self.toggl_weather.setCheckable(True)
        self.toggl_weather.setAutoExclusive(False)
        self.toggl_weather.setObjectName(_fromUtf8("toggl_weather"))
        self.toggles.addWidget(self.toggl_weather, QtCore.Qt.AlignTop)
        self.toggl_waves = QtGui.QRadioButton(self.toggle_tab)
        self.toggl_waves.setCheckable(True)
        self.toggl_waves.setAutoExclusive(False)
        self.toggl_waves.setObjectName(_fromUtf8("toggl_waves"))
        self.toggles.addWidget(self.toggl_waves, QtCore.Qt.AlignTop)
        self.toggles_layout.addLayout(self.toggles)
        self.control_tabs.addTab(self.toggle_tab, _fromUtf8(""))
        self.plot_tab = QtGui.QWidget()
        self.plot_tab.setObjectName(_fromUtf8("plot_tab"))
        self.plot_tab_layout = QtGui.QVBoxLayout(self.plot_tab)
        self.plot_tab_layout.setObjectName(_fromUtf8("plot_tab_layout"))
        self.plot_start_btn = QtGui.QPushButton(self.plot_tab)
        self.plot_start_btn.setObjectName(_fromUtf8("plot_start_btn"))
        self.plot_tab_layout.addWidget(self.plot_start_btn)
        self.plot_finish_btn = QtGui.QPushButton(self.plot_tab)
        self.plot_finish_btn.setObjectName(_fromUtf8("plot_finish_btn"))
        self.plot_tab_layout.addWidget(self.plot_finish_btn)
        self.speed_output_form_layout = QtGui.QFormLayout()
        self.speed_output_form_layout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.speed_output_form_layout.setObjectName(_fromUtf8("speed_output_form_layout"))
        self.elot_label = QtGui.QLabel(self.plot_tab)
        self.elot_label.setObjectName(_fromUtf8("elot_label"))
        self.speed_output_form_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.elot_label)
        self.elot_input = QtGui.QDoubleSpinBox(self.plot_tab)
        self.elot_input.setObjectName(_fromUtf8("elot_input"))
        self.speed_output_form_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.elot_input)
        self.output_label = QtGui.QLabel(self.plot_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_label.sizePolicy().hasHeightForWidth())
        self.output_label.setSizePolicy(sizePolicy)
        self.output_label.setTextFormat(QtCore.Qt.AutoText)
        self.output_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_label.setObjectName(_fromUtf8("output_label"))
        self.speed_output_form_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.output_label)
        self.output_line = QtGui.QFrame(self.plot_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_line.sizePolicy().hasHeightForWidth())
        self.output_line.setSizePolicy(sizePolicy)
        self.output_line.setFrameShape(QtGui.QFrame.HLine)
        self.output_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.output_line.setObjectName(_fromUtf8("output_line"))
        self.speed_output_form_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.output_line)
        self.CtS_label = QtGui.QLabel(self.plot_tab)
        self.CtS_label.setObjectName(_fromUtf8("CtS_label"))
        self.speed_output_form_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.CtS_label)
        self.CtS_output_fr = QtGui.QFrame(self.plot_tab)
        self.CtS_output_fr.setFrameShape(QtGui.QFrame.StyledPanel)
        self.CtS_output_fr.setFrameShadow(QtGui.QFrame.Raised)
        self.CtS_output_fr.setObjectName(_fromUtf8("CtS_output_fr"))
        self.cts_output_fr_layout = QtGui.QGridLayout(self.CtS_output_fr)
        self.cts_output_fr_layout.setObjectName(_fromUtf8("cts_output_fr_layout"))
        self.CtS_output_label = QtGui.QLabel(self.CtS_output_fr)
        self.CtS_output_label.setObjectName(_fromUtf8("CtS_output_label"))
        self.cts_output_fr_layout.addWidget(self.CtS_output_label, 0, 0, 1, 1)
        self.speed_output_form_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.CtS_output_fr)
        self.plot_tab_layout.addLayout(self.speed_output_form_layout)
        self.calculate_btn = QtGui.QPushButton(self.plot_tab)
        self.calculate_btn.setObjectName(_fromUtf8("calculate_btn"))
        self.plot_tab_layout.addWidget(self.calculate_btn)
        self.plot_start_btn.raise_()
        self.plot_finish_btn.raise_()
        self.calculate_btn.raise_()
        self.control_tabs.addTab(self.plot_tab, _fromUtf8(""))
        self.control_panel.addWidget(self.control_tabs)
        self.spacer_line_bottom = QtGui.QFrame(self.layoutWidget)
        self.spacer_line_bottom.setFrameShape(QtGui.QFrame.HLine)
        self.spacer_line_bottom.setFrameShadow(QtGui.QFrame.Sunken)
        self.spacer_line_bottom.setObjectName(_fromUtf8("spacer_line_bottom"))
        self.control_panel.addWidget(self.spacer_line_bottom)
        self.zoom_in_btn = QtGui.QPushButton(self.layoutWidget)
        self.zoom_in_btn.setObjectName(_fromUtf8("zoom_in_btn"))
        self.control_panel.addWidget(self.zoom_in_btn)
        self.zoom_out_btn = QtGui.QPushButton(self.layoutWidget)
        self.zoom_out_btn.setObjectName(_fromUtf8("zoom_out_btn"))
        self.control_panel.addWidget(self.zoom_out_btn)
        spacerItem = QtGui.QSpacerItem(20, 1000, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.control_panel.addItem(spacerItem)
        self.central_widget_layout.addWidget(self.mapcontr_splitter)
        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar = QtGui.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 904, 36))
        self.menu_bar.setObjectName(_fromUtf8("menu_bar"))
        self.file_menu = QtGui.QMenu(self.menu_bar)
        self.file_menu.setObjectName(_fromUtf8("file_menu"))
        self.edit_menu = QtGui.QMenu(self.menu_bar)
        self.edit_menu.setObjectName(_fromUtf8("edit_menu"))
        self.import_menu = QtGui.QMenu(self.menu_bar)
        self.import_menu.setObjectName(_fromUtf8("import_menu"))
        MainWindow.setMenuBar(self.menu_bar)
        self.status_bar = QtGui.QStatusBar(MainWindow)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        MainWindow.setStatusBar(self.status_bar)
        self.save_action = QtGui.QAction(MainWindow)
        self.save_action.setObjectName(_fromUtf8("save_action"))
        self.saveAs_action = QtGui.QAction(MainWindow)
        self.saveAs_action.setObjectName(_fromUtf8("saveAs_action"))
        self.import_action = QtGui.QAction(MainWindow)
        self.import_action.setObjectName(_fromUtf8("import_action"))
        self.quit_action = QtGui.QAction(MainWindow)
        self.quit_action.setObjectName(_fromUtf8("quit_action"))
        self.import_boats_action = QtGui.QAction(MainWindow)
        self.import_boats_action.setObjectName(_fromUtf8("import_boats_action"))
        self.import_weather_action = QtGui.QAction(MainWindow)
        self.import_weather_action.setObjectName(_fromUtf8("import_weather_action"))
        self.import_temps_action = QtGui.QAction(MainWindow)
        self.import_temps_action.setObjectName(_fromUtf8("import_temps_action"))
        self.imp_waves_action = QtGui.QAction(MainWindow)
        self.imp_waves_action.setObjectName(_fromUtf8("imp_waves_action"))
        self.actionToggle_Course = QtGui.QAction(MainWindow)
        self.actionToggle_Course.setObjectName(_fromUtf8("actionToggle_Course"))
        self.actionToggle_Weather = QtGui.QAction(MainWindow)
        self.actionToggle_Weather.setCheckable(True)
        self.actionToggle_Weather.setObjectName(_fromUtf8("actionToggle_Weather"))
        self.actionToggle_Waves = QtGui.QAction(MainWindow)
        self.actionToggle_Waves.setCheckable(True)
        self.actionToggle_Waves.setObjectName(_fromUtf8("actionToggle_Waves"))
        self.actionToggle_Boats = QtGui.QAction(MainWindow)
        self.actionToggle_Boats.setCheckable(True)
        self.actionToggle_Boats.setObjectName(_fromUtf8("actionToggle_Boats"))
        self.actionToggle_Toolbar = QtGui.QAction(MainWindow)
        self.actionToggle_Toolbar.setCheckable(True)
        self.actionToggle_Toolbar.setObjectName(_fromUtf8("actionToggle_Toolbar"))
        self.actionToggle_Temprature = QtGui.QAction(MainWindow)
        self.actionToggle_Temprature.setObjectName(_fromUtf8("actionToggle_Temprature"))
        self.preferences_action = QtGui.QAction(MainWindow)
        self.preferences_action.setObjectName(_fromUtf8("preferences_action"))
        self.corner_coors_input_action = QtGui.QAction(MainWindow)
        self.corner_coors_input_action.setObjectName(_fromUtf8("corner_coors_input_action"))
        self.actionPlot_Course = QtGui.QAction(MainWindow)
        self.actionPlot_Course.setCheckable(True)
        self.actionPlot_Course.setObjectName(_fromUtf8("actionPlot_Course"))
        self.actionZoom_in = QtGui.QAction(MainWindow)
        self.actionZoom_in.setObjectName(_fromUtf8("actionZoom_in"))
        self.file_menu.addAction(self.save_action)
        self.file_menu.addAction(self.saveAs_action)
        self.file_menu.addAction(self.import_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.quit_action)
        self.file_menu.addAction(self.preferences_action)
        self.edit_menu.addAction(self.corner_coors_input_action)
        self.import_menu.addAction(self.import_boats_action)
        self.import_menu.addAction(self.import_weather_action)
        self.menu_bar.addAction(self.file_menu.menuAction())
        self.menu_bar.addAction(self.edit_menu.menuAction())
        self.menu_bar.addAction(self.import_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.control_tabs.setCurrentIndex(1)
        QtCore.QObject.connect(self.zoom_in_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionZoom_in.hover)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "N-nav", None))
        self.nnav_label.setText(_translate("MainWindow", "N-nav", None))
        self.toggl_course.setText(_translate("MainWindow", "Course", None))
        self.toggl_traff.setText(_translate("MainWindow", "Traffic", None))
        self.toggl_weather.setText(_translate("MainWindow", "Weather", None))
        self.toggl_waves.setText(_translate("MainWindow", "Waves", None))
        self.control_tabs.setTabText(self.control_tabs.indexOf(self.toggle_tab), _translate("MainWindow", "Toggles", None))
        self.plot_start_btn.setText(_translate("MainWindow", "Plot Start", None))
        self.plot_finish_btn.setText(_translate("MainWindow", "Plot Finish", None))
        self.elot_label.setText(_translate("MainWindow", "Speed of travel (kn)", None))
        self.output_label.setText(_translate("MainWindow", "Output", None))
        self.CtS_label.setText(_translate("MainWindow", "Course to Steer: ", None))
        self.CtS_output_label.setText(_translate("MainWindow", "CtS", None))
        self.calculate_btn.setText(_translate("MainWindow", "Calculate", None))
        self.control_tabs.setTabText(self.control_tabs.indexOf(self.plot_tab), _translate("MainWindow", "Plot", None))
        self.zoom_in_btn.setText(_translate("MainWindow", "Zoom In", None))
        self.zoom_out_btn.setText(_translate("MainWindow", "Zoom Out", None))
        self.file_menu.setTitle(_translate("MainWindow", "File", None))
        self.edit_menu.setTitle(_translate("MainWindow", "Edit", None))
        self.import_menu.setTitle(_translate("MainWindow", "Import", None))
        self.save_action.setText(_translate("MainWindow", "Save", None))
        self.save_action.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.saveAs_action.setText(_translate("MainWindow", "Save As...", None))
        self.saveAs_action.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.import_action.setText(_translate("MainWindow", "Import", None))
        self.import_action.setShortcut(_translate("MainWindow", "Ctrl+I", None))
        self.quit_action.setText(_translate("MainWindow", "Quit", None))
        self.quit_action.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.import_boats_action.setText(_translate("MainWindow", "Boats", None))
        self.import_weather_action.setText(_translate("MainWindow", "Weather", None))
        self.import_temps_action.setText(_translate("MainWindow", "Temprature", None))
        self.imp_waves_action.setText(_translate("MainWindow", "Waves", None))
        self.actionToggle_Course.setText(_translate("MainWindow", "Toggle Course", None))
        self.actionToggle_Weather.setText(_translate("MainWindow", "ToggleWeather", None))
        self.actionToggle_Waves.setText(_translate("MainWindow", "Toggle Waves", None))
        self.actionToggle_Boats.setText(_translate("MainWindow", "Toggle Boats", None))
        self.actionToggle_Toolbar.setText(_translate("MainWindow", "View/Hide Toolbar", None))
        self.actionToggle_Temprature.setText(_translate("MainWindow", "Toggle Temprature", None))
        self.preferences_action.setText(_translate("MainWindow", "Preferences", None))
        self.corner_coors_input_action.setText(_translate("MainWindow", "Corner Coordinates", None))
        self.actionPlot_Course.setText(_translate("MainWindow", "Plot Course", None))
        self.actionPlot_Course.setToolTip(_translate("MainWindow", "plot course", None))
        self.actionZoom_in.setText(_translate("MainWindow", "zoom_in", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

